config/routes.rb
Medspace2::Application.routes.draw do

  ## Forums
  match '/forum' => 'forum#index', :as => 'forum_posts'
  match '/your_genome' => 'personal/genome#index', :as => 'your_genome'
  match '/prescriptions' => 'personal/prescriptions#index', :as => 'your_prescriptions'
  match '/training' => 'personal/training#index', :as => 'your_training'

  root :to => 'home#index'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  #match ':controller(/:action(/:id))(.:format)'
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :message
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/forum_controller.rb
class ForumController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/personal/genome_controller.rb
class Personal::GenomeController < ApplicationController
  def index
  end
end

app/controllers/personal/prescriptions_controller.rb
class Personal::PrescriptionsController < ApplicationController
  def index
  end
end

app/controllers/personal/training_controller.rb
class Personal::TrainingController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/personal/genome_helper.rb
module Personal::GenomeHelper
end

app/views/forum/index.html.erb
<% @posts.each do |post| %>
 <div style="background: #cccccc; padding: 10px">
 <%= post.title %>
 </div>
 <div style="padding: 10px">
 <%= post.message %>
 </div>
 
<% end %>

app/views/home/index.html.erb
<div class="hero-unit">
<h2>Welcome to MSH Health Space</h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Health Space</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>
    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Health Space</a>
          <div class="btn-group pull-right">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-user"></i> Username
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="#">Profile</a></li>
              <li class="divider"></li>
              <li><a href="#">Sign Out</a></li>
            </ul>
          </div>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><%= link_to 'Home', root_url %></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">About you</li>
              <li><%= link_to 'Your prescriptions', your_prescriptions_url %></li>
              <li><%= link_to 'Your training', your_training_url %></li>
              <li><%= link_to 'Your genome', your_genome_url %></li>
              <li class="nav-header">Discussions</li>
              <li><%= link_to 'Forum', forum_posts_url %></li>
              <li class="nav-header">About</li>
              <li><a href="http://www.innovativemedicine.ca/about">About Personalized Genomics</a></li>
              <li><a href="http://www.mountsinai.on.ca/about_us">About MSH</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
				<%= yield %>
        </div><!--/span-->
     </div><!--/row-->

      <hr>

      <footer>
        <p>© innovativemedicine.ca 2012</p>
      </footer>

    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!--
    <script src="./Bootstrap, from Twitter_files/jquery.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-transition.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-alert.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-modal.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-dropdown.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-scrollspy.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-tab.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-tooltip.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-popover.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-button.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-collapse.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-carousel.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-typeahead.js"></script>

   -->
  

</body></html>

app/views/personal/genome/index.html.erb
<h2>Welcome to your personal genome page</h2>

<%= link_to 'Read about your variants', '' %>

app/views/personal/prescriptions/index.html.erb
<h2>Manage your prescriptions</h2>

app/views/personal/training/index.html.erb
<h2>Manage your personal training</h2>